apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 1
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
        - name: vprodb
          image: vprofile/vprofiledb:V1
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: vprod-db-data
          ports:
            - name: vprodb-port
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-pass
      nodeSelector:
        zone: us-east-2a
      volumes:
        - name: vprod-db-data
          awsElasticBlockStore:
            volumeID: vol-01f84e5dcc682d5e7
            fsType: ext4
        #make sure to tag this volume with Key: KubernetesCluster and Value: vprokube.mandohashdevops.com
      initContainers:
        #By default, lost+found is created when you format the disk with ext4. In order for mysql to work
        #This /var/lib/mysql location should be empty, so this init container will delete the data before launching the actual pod
        - name: busybox 
          image: busybox:latest #lightweight linux container
          args: ["rm", "-rf", "/var/lib/mysql/lost+found"]
          volumeMounts:
            - name: vprod-db-data
              mountPath: /var/lib/mysql